# Generated by Django 6.0.1 on 2026-04-04 21:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departements', '0001_initial'),
        ('employes', '0001_initial'),
        ('postes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employe',
            options={'ordering': ['nom', 'prenom'], 'verbose_name': 'Employé', 'verbose_name_plural': 'Employés'},
        ),
        migrations.AddField(
            model_name='employe',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='employe',
            name='date_modification',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='employe',
            name='departement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employes', to='departements.departement'),
        ),
        migrations.AlterField(
            model_name='employe',
            name='poste',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employes', to='postes.poste'),
        ),
        migrations.AlterField(
            model_name='employe',
            name='utilisateur',
            field=models.OneToOneField(help_text='Utilisateur associé à cet employé', on_delete=django.db.models.deletion.CASCADE, related_name='employe', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='employe',
            index=models.Index(fields=['nom', 'prenom'], name='employes_em_nom_19f0a2_idx'),
        ),
        migrations.AddIndex(
            model_name='employe',
            index=models.Index(fields=['email'], name='employes_em_email_3c57e0_idx'),
        ),
    ]
