# Generated by Django 6.0.1 on 2026-05-05 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employes', '0002_alter_employe_options_employe_date_creation_and_more'),
        ('paies', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paie',
            options={'verbose_name': 'employe'},
        ),
        migrations.AddIndex(
            model_name='paie',
            index=models.Index(fields=['employe', 'mois', 'salaire_base'], name='paies_paie_employe_84c53c_idx'),
        ),
    ]
